version: '3.8'
services:
  client:
    build: .
    container_name: react-redux-demo-2-client-frontend
    ports:
      - '2026:3000'
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    network_mode: bridge